//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LIMS_DEMO.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CustomerMaster()
        {
            this.EnquiryMasters = new HashSet<EnquiryMaster>();
        }
    
        public int CustomerMasterId { get; set; }
        public byte CustomerTypeId { get; set; }
        public Nullable<byte> CompanyTypeId { get; set; }
        public byte CustomerGroupId { get; set; }
        public Nullable<System.DateTime> RegistrationDate { get; set; }
        public string RegistrationName { get; set; }
        public string NameTitle { get; set; }
        public string ContactPersonName { get; set; }
        public string ContactDesignation { get; set; }
        public string ContactMobileNo { get; set; }
        public string ContactEmail { get; set; }
        public string Address1 { get; set; }
        public string WardNo { get; set; }
        public string Taluka { get; set; }
        public string Village { get; set; }
        public string Area { get; set; }
        public string CityName { get; set; }
        public string StateName { get; set; }
        public string CountryName { get; set; }
        public string Pincode { get; set; }
        public string PhoneNo { get; set; }
        public string MobileNo { get; set; }
        public string Email { get; set; }
        public string PANNo { get; set; }
        public string PANUpload { get; set; }
        public string AddressProofUpload { get; set; }
        public string CINNumber { get; set; }
        public string GSTNo { get; set; }
        public string FaxNo { get; set; }
        public bool IsActive { get; set; }
        public int EnteredBy { get; set; }
        public System.DateTime EnteredDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public byte[] ModifiedDate { get; set; }
    
        public virtual CompanyTypeMaster CompanyTypeMaster { get; set; }
        public virtual CustomerGroupMaster CustomerGroupMaster { get; set; }
        public virtual CustomerTypeMaster CustomerTypeMaster { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EnquiryMaster> EnquiryMasters { get; set; }
    }
}
