//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LIMS_DEMO.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class EnquiryParameterDetail
    {
        public long EnquiryParameterDetailID { get; set; }
        public long EnquirySampleID { get; set; }
        public int ParameterMappingId { get; set; }
        public Nullable<int> UnitId { get; set; }
        public Nullable<int> TestMethodId { get; set; }
        public Nullable<int> LabMasterId { get; set; }
        public Nullable<decimal> LowerLimit { get; set; }
        public Nullable<decimal> UpperLimit { get; set; }
        public string PCBLimit { get; set; }
        public Nullable<decimal> Charges { get; set; }
        public bool IsActive { get; set; }
        public int EnteredBy { get; set; }
        public System.DateTime EnteredDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public byte[] ModifiedDate { get; set; }
        public string Remarks { get; set; }
    
        public virtual EnquirySampleDetail EnquirySampleDetail { get; set; }
        public virtual LabMaster LabMaster { get; set; }
        public virtual ParameterMapping ParameterMapping { get; set; }
        public virtual TestMethod TestMethod { get; set; }
        public virtual UnitMaster UnitMaster { get; set; }
    }
}
