//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LIMS_DEMO.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class EnquiryDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EnquiryDetail()
        {
            this.EnquirySampleDetails = new HashSet<EnquirySampleDetail>();
        }
    
        public long EnquiryDetailId { get; set; }
        public Nullable<long> EnquiryId { get; set; }
        public Nullable<int> ProductGroupId { get; set; }
        public Nullable<int> SubGroupId { get; set; }
        public Nullable<int> MatrixId { get; set; }
        public Nullable<bool> IsApprove { get; set; }
        public Nullable<int> ApprovedBy { get; set; }
        public Nullable<System.DateTime> ApproveDate { get; set; }
        public Nullable<bool> IsReject { get; set; }
        public Nullable<int> RejectedBy { get; set; }
        public Nullable<System.DateTime> RejectDate { get; set; }
        public bool IsActive { get; set; }
        public int EnteredBy { get; set; }
        public System.DateTime EnteredDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public byte[] ModifiedDate { get; set; }
        public Nullable<int> WorkOrderID { get; set; }
        public Nullable<int> SampleTypeProductId { get; set; }
        public Nullable<long> EnquiryMasterSampleTypeId { get; set; }
    
        public virtual EnquiryMaster EnquiryMaster { get; set; }
        public virtual MatrixMaster MatrixMaster { get; set; }
        public virtual ProductGroupMaster ProductGroupMaster { get; set; }
        public virtual SubGroupMaster SubGroupMaster { get; set; }
        public virtual EnquiryMasterSampleType EnquiryMasterSampleType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EnquirySampleDetail> EnquirySampleDetails { get; set; }
        public virtual MatrixMaster MatrixMaster1 { get; set; }
        public virtual ProductGroupMaster ProductGroupMaster1 { get; set; }
        public virtual SubGroupMaster SubGroupMaster1 { get; set; }
    }
}
