//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LIMS_DEMO.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ErrorLog
    {
        public long ErrorLogId { get; set; }
        public string SPNAME { get; set; }
        public string ERRORNUMBER { get; set; }
        public string ERRORSEVERITY { get; set; }
        public string ERRORSTATE { get; set; }
        public string ERRORMESSAGE { get; set; }
        public string ErrorType { get; set; }
        public Nullable<System.DateTime> ErrorLogDateTime { get; set; }
    }
}
