//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LIMS_DEMO.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class FDStackEmission
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FDStackEmission()
        {
            this.FDStack_ParameterData = new HashSet<FDStack_ParameterData>();
            this.FDStackEmission_IsoKinetic = new HashSet<FDStackEmission_IsoKinetic>();
            this.FDStackEmission_GaseousData = new HashSet<FDStackEmission_GaseousData>();
            this.FDStackEmission_Details = new HashSet<FDStackEmission_Details>();
        }
    
        public long FDStackEmissionId { get; set; }
        public Nullable<long> EnquiryId { get; set; }
        public long SampleCollectionId { get; set; }
        public Nullable<byte> StatusId { get; set; }
        public string InstrumentId { get; set; }
        public Nullable<decimal> BarometricPressure { get; set; }
        public Nullable<decimal> FlueGasComposition_CO2 { get; set; }
        public Nullable<decimal> FlueGasComposition_O2 { get; set; }
        public Nullable<decimal> FlueGasComposition_CO { get; set; }
        public Nullable<decimal> FlueGasComposition_N2 { get; set; }
        public Nullable<decimal> MoistureContent { get; set; }
        public Nullable<decimal> DurationOfBoiler { get; set; }
        public Nullable<decimal> AmbientTemperature { get; set; }
        public Nullable<decimal> StackTemperature { get; set; }
        public Nullable<decimal> VelocityofStackGas { get; set; }
        public Nullable<decimal> PitotTubefactor { get; set; }
        public Nullable<decimal> StaticPressure { get; set; }
        public Nullable<decimal> AbsoluteStackPressure { get; set; }
        public Nullable<decimal> FlueGasQuantity { get; set; }
        public Nullable<double> ThimbleNO { get; set; }
        public Nullable<decimal> TotalGasPassed { get; set; }
        public Nullable<decimal> SamplingGasTemp_Initial { get; set; }
        public Nullable<decimal> SamplingGasTemp_Final { get; set; }
        public Nullable<decimal> SamplingGasTemp_Average { get; set; }
        public Nullable<decimal> Vsc { get; set; }
        public bool IsActive { get; set; }
        public int EnteredBy { get; set; }
        public System.DateTime EnteredDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public byte[] ModifiedDate { get; set; }
        public Nullable<decimal> Bwo { get; set; }
        public Nullable<decimal> AmbientTempC { get; set; }
        public Nullable<decimal> StackTempC { get; set; }
        public Nullable<decimal> C { get; set; }
        public string StackIdentity { get; set; }
        public string StackAttachedTo { get; set; }
        public string MaterialOfConstruction { get; set; }
        public string StackHeight { get; set; }
        public Nullable<int> StackDiameter { get; set; }
        public Nullable<int> HeightOfPorthole { get; set; }
        public string StackShapeTop { get; set; }
        public Nullable<int> StackArea { get; set; }
        public string Fuelused_Type { get; set; }
        public string Fuelused_Consumption { get; set; }
        public Nullable<bool> Is8DAnd2D { get; set; }
        public Nullable<bool> Samplingportandplatformexists { get; set; }
        public Nullable<bool> Airpollutioncontrolequipmentexists { get; set; }
        public Nullable<int> Velocity_V { get; set; }
        public Nullable<int> Vf { get; set; }
        public Nullable<int> Va { get; set; }
        public Nullable<int> Pf { get; set; }
        public Nullable<int> Pi { get; set; }
        public Nullable<int> Tf { get; set; }
        public Nullable<int> Ti { get; set; }
        public Nullable<int> Pstd { get; set; }
        public Nullable<int> Tstd { get; set; }
        public string LoadAtMonitoring { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FDStack_ParameterData> FDStack_ParameterData { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FDStackEmission_IsoKinetic> FDStackEmission_IsoKinetic { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FDStackEmission_GaseousData> FDStackEmission_GaseousData { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FDStackEmission_Details> FDStackEmission_Details { get; set; }
        public virtual SampleCollection SampleCollection { get; set; }
        public virtual StatusMaster StatusMaster { get; set; }
    }
}
