//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LIMS_DEMO.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class FDStackEmission_IsoKinetic
    {
        public long FDStackEmission_IsoKineticId { get; set; }
        public long FDStackEmissionId { get; set; }
        public Nullable<decimal> SamplingFlowRate { get; set; }
        public Nullable<decimal> SamplingDuration { get; set; }
        public Nullable<decimal> VacuumPv_Initial { get; set; }
        public Nullable<decimal> VacuumPv_Final { get; set; }
        public Nullable<decimal> VacuumPv_Average { get; set; }
        public bool IsActive { get; set; }
        public int EnteredBy { get; set; }
        public System.DateTime EnteredDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public byte[] ModifiedDate { get; set; }
        public Nullable<decimal> DryGasFinal { get; set; }
        public Nullable<decimal> DryGasInitial { get; set; }
        public Nullable<decimal> DryGasDiff { get; set; }
        public Nullable<decimal> NozzleConstantArea { get; set; }
    
        public virtual FDStackEmission FDStackEmission { get; set; }
    }
}
