//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LIMS_DEMO.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class FDStackEmission_GaseousData
    {
        public long FDStackEmission_GaseousDataId { get; set; }
        public long FDStackEmissionId { get; set; }
        public Nullable<decimal> FlowRate { get; set; }
        public string SamplingTime { get; set; }
        public Nullable<decimal> GasTemp { get; set; }
        public Nullable<decimal> BarometricPressure { get; set; }
        public Nullable<decimal> DryGasMeterReading_Initial { get; set; }
        public Nullable<decimal> DryGasMeterReading_Final { get; set; }
        public Nullable<decimal> DryGasMeterReading_Total { get; set; }
        public Nullable<int> BottleNo { get; set; }
        public string AbsorbingSolutionUsed_solution { get; set; }
        public Nullable<decimal> AbsorbingSolutionUsed_Conc { get; set; }
        public Nullable<decimal> AbsorbingSolutionUsed_Vol { get; set; }
        public string PreservationDone { get; set; }
        public bool IsActive { get; set; }
        public int EnteredBy { get; set; }
        public System.DateTime EnteredDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public byte[] ModifiedDate { get; set; }
        public string Vs { get; set; }
        public string Parameters { get; set; }
        public string TestMethodName { get; set; }
        public Nullable<bool> InField { get; set; }
        public Nullable<bool> IsNABLAccredited { get; set; }
    
        public virtual FDStackEmission FDStackEmission { get; set; }
    }
}
