//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LIMS_DEMO.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class FieldWorkplaceEnvironmentAndFugitiveEmission
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FieldWorkplaceEnvironmentAndFugitiveEmission()
        {
            this.FieldWorkplaceGasSamplings = new HashSet<FieldWorkplaceGasSampling>();
        }
    
        public int WorkplaceID { get; set; }
        public long SampleCollectionId { get; set; }
        public Nullable<long> EnquiryId { get; set; }
        public Nullable<byte> StatusId { get; set; }
        public Nullable<System.DateTime> SurveyDate { get; set; }
        public Nullable<int> InstrumentId { get; set; }
        public Nullable<int> DurationOfSampling { get; set; }
        public string FilterPaperAnalyzed { get; set; }
        public Nullable<int> FilterPaperNo { get; set; }
        public Nullable<int> FlowRate_Final { get; set; }
        public Nullable<int> FlowRate_Initial { get; set; }
        public Nullable<int> FlowRate_Avg { get; set; }
        public Nullable<int> Sampling_Duration { get; set; }
        public string RelativeHumidity { get; set; }
        public string Temperature { get; set; }
        public string AnyObservation { get; set; }
        public bool IsActive { get; set; }
        public int EnteredBy { get; set; }
        public System.DateTime EnteredDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public byte[] ModifiedDate { get; set; }
        public Nullable<int> FilterPaperNo2 { get; set; }
        public Nullable<int> StartTime { get; set; }
        public Nullable<int> EndTime { get; set; }
        public Nullable<int> TotalVolAirPassed_L { get; set; }
        public Nullable<int> TotalVolumeAirPassed_m3 { get; set; }
        public Nullable<int> AvgFlowRate { get; set; }
    
        public virtual SampleCollection SampleCollection { get; set; }
        public virtual StatusMaster StatusMaster { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FieldWorkplaceGasSampling> FieldWorkplaceGasSamplings { get; set; }
    }
}
