//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LIMS_DEMO.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class FieldAmbientAirGasesSampling
    {
        public int GasesSampledId { get; set; }
        public Nullable<int> FieldId { get; set; }
        public string GasesSampled { get; set; }
        public Nullable<int> VolImpingingSolution { get; set; }
        public Nullable<int> BottleNo { get; set; }
        public Nullable<int> RotaMeterFlow { get; set; }
        public Nullable<int> Duration { get; set; }
        public Nullable<int> Vs { get; set; }
        public string PreservationDone { get; set; }
        public bool IsActive { get; set; }
        public int EnteredBy { get; set; }
        public System.DateTime EnteredDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public byte[] ModifiedDate { get; set; }
        public Nullable<int> ParameterMappingId { get; set; }
        public Nullable<bool> Testing { get; set; }
        public Nullable<int> ShiftNoGases { get; set; }
    
        public virtual FieldAmbientAirMonitoring FieldAmbientAirMonitoring { get; set; }
        public virtual ParameterMapping ParameterMapping { get; set; }
    }
}
