//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LIMS_DEMO.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class FieldWorkplaceGasSampling
    {
        public int WorkplaceGasID { get; set; }
        public Nullable<int> WorkplaceID { get; set; }
        public string Parameters { get; set; }
        public string VolImpingingSol { get; set; }
        public string BottleNo { get; set; }
        public Nullable<int> RotameterFlow { get; set; }
        public Nullable<int> Duration { get; set; }
        public bool IsActive { get; set; }
        public int EnteredBy { get; set; }
        public System.DateTime EnteredDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public byte[] ModifiedDate { get; set; }
        public string TestMethodName { get; set; }
        public Nullable<bool> InField { get; set; }
        public Nullable<bool> IsNABLAccredited { get; set; }
        public Nullable<int> Vs { get; set; }
        public string PreservationDone { get; set; }
    
        public virtual FieldWorkplaceEnvironmentAndFugitiveEmission FieldWorkplaceEnvironmentAndFugitiveEmission { get; set; }
    }
}
