//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LIMS_DEMO.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class FieldAmbientAirMatterSize
    {
        public int MatterSizeId { get; set; }
        public Nullable<int> FieldId { get; set; }
        public string MatterSize { get; set; }
        public Nullable<int> FilterPaperNo { get; set; }
        public Nullable<int> CycloneCupNo { get; set; }
        public Nullable<int> FlowRateFinal { get; set; }
        public Nullable<int> FlowRateInitial { get; set; }
        public Nullable<int> FlowRateDiff { get; set; }
        public Nullable<int> TimeTotalizerFinal { get; set; }
        public Nullable<int> TimeTotalizerInitial { get; set; }
        public Nullable<int> TimeTotalizerDiff { get; set; }
        public Nullable<int> SamplingDurationFinal { get; set; }
        public Nullable<int> SamplingDurationInitial { get; set; }
        public Nullable<int> SamplingDurationDiff { get; set; }
        public bool IsActive { get; set; }
        public int EnteredBy { get; set; }
        public System.DateTime EnteredDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public byte[] ModifiedDate { get; set; }
        public Nullable<int> ShiftNo { get; set; }
        public Nullable<System.TimeSpan> MatterSizeStartTime { get; set; }
        public Nullable<System.TimeSpan> MatterSizeEndTime { get; set; }
    
        public virtual FieldAmbientAirMonitoring FieldAmbientAirMonitoring { get; set; }
    }
}
