//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LIMS_DEMO.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class FieldWasteWater
    {
        public int WasteWaterID { get; set; }
        public Nullable<long> EnquiryId { get; set; }
        public long SampleCollectionId { get; set; }
        public Nullable<byte> StatusId { get; set; }
        public string Parameters { get; set; }
        public string TestResults { get; set; }
        public string AnyOtherObservation { get; set; }
        public string WaterUse { get; set; }
        public bool IsActive { get; set; }
        public int EnteredBy { get; set; }
        public System.DateTime EnteredDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public byte[] ModifiedDate { get; set; }
        public Nullable<int> ParameterMappingId { get; set; }
        public string TestMethodName { get; set; }
        public Nullable<bool> InField { get; set; }
        public Nullable<bool> IsNABLAccredited { get; set; }
    
        public virtual ParameterMapping ParameterMapping { get; set; }
        public virtual SampleCollection SampleCollection { get; set; }
        public virtual StatusMaster StatusMaster { get; set; }
    }
}
