//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LIMS_DEMO.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class FieldNoiseLevelMonitoringParameter
    {
        public int ParameterId { get; set; }
        public Nullable<int> FieldNoiseId { get; set; }
        public string FileName { get; set; }
        public string TimeDuration { get; set; }
        public string ParameterName { get; set; }
        public string TestMethodName { get; set; }
        public Nullable<bool> InField { get; set; }
        public Nullable<bool> IsNABLAccredited { get; set; }
        public string DayNight { get; set; }
        public string LocationGrid { get; set; }
        public Nullable<long> LeqFastResponse { get; set; }
        public Nullable<long> LeqSlowResponse { get; set; }
        public Nullable<long> L10FastResponse { get; set; }
        public Nullable<long> L10SlowResponse { get; set; }
        public Nullable<long> L50FastResponse { get; set; }
        public Nullable<long> L50SlowResponse { get; set; }
        public Nullable<long> L90FastResponse { get; set; }
        public Nullable<long> L90SlowResponse { get; set; }
        public Nullable<long> LminFastResponse { get; set; }
        public Nullable<long> LminSlowResponse { get; set; }
        public Nullable<long> LmaxFastResponse { get; set; }
        public Nullable<long> LmaxSlowResponse { get; set; }
        public bool IsActive { get; set; }
        public int EnteredBy { get; set; }
        public System.DateTime EnteredDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public byte[] ModifiedDate { get; set; }
        public string ShiftName { get; set; }
    
        public virtual FieldNoiseLevelMonitoring FieldNoiseLevelMonitoring { get; set; }
    }
}
