//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LIMS_DEMO.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class FieldNoiseSourceParameter
    {
        public int NoiseSourceParameterId { get; set; }
        public Nullable<int> FieldNoiseId { get; set; }
        public string ParameterName { get; set; }
        public string TestMethodName { get; set; }
        public string LocationGrid { get; set; }
        public string DayNight { get; set; }
        public string UnitUsed { get; set; }
        public Nullable<long> TimeSource { get; set; }
        public string ShiftName { get; set; }
        public Nullable<long> Inside { get; set; }
        public Nullable<long> Outside { get; set; }
        public Nullable<long> InsertionLoss { get; set; }
        public Nullable<bool> InField { get; set; }
        public Nullable<bool> IsNABLAccredited { get; set; }
        public bool IsActive { get; set; }
        public int EnteredBy { get; set; }
        public System.DateTime EnteredDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public byte[] ModifiedDate { get; set; }
    
        public virtual FieldNoiseLevelMonitoring FieldNoiseLevelMonitoring { get; set; }
    }
}
