//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LIMS_DEMO.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class FieldMicrobiologicalMonitoringOfAir
    {
        public int MicrobiologicalID { get; set; }
        public Nullable<long> EnquiryId { get; set; }
        public long SampleCollectionId { get; set; }
        public Nullable<byte> StatusId { get; set; }
        public string FlowRate { get; set; }
        public string AreaSwabbed { get; set; }
        public string MediaUsed { get; set; }
        public string IndustryType { get; set; }
        public Nullable<int> EquipmentId { get; set; }
        public string RelativeHumidity { get; set; }
        public string AnyOtherObservation { get; set; }
        public bool IsActive { get; set; }
        public int EnteredBy { get; set; }
        public System.DateTime EnteredDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public byte[] ModifiedDate { get; set; }
    
        public virtual SampleCollection SampleCollection { get; set; }
        public virtual StatusMaster StatusMaster { get; set; }
    }
}
