//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LIMS_DEMO.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class FieldNoiseLevelMonitoring
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public FieldNoiseLevelMonitoring()
        {
            this.FieldNoiseSourceParameters = new HashSet<FieldNoiseSourceParameter>();
            this.FieldNoiseLevelMonitoringParameters = new HashSet<FieldNoiseLevelMonitoringParameter>();
        }
    
        public int FieldNoiseId { get; set; }
        public Nullable<long> EnquiryId { get; set; }
        public Nullable<long> SampleCollectionId { get; set; }
        public Nullable<byte> StatusId { get; set; }
        public string Location { get; set; }
        public string LocationArea { get; set; }
        public Nullable<long> LocationHeight { get; set; }
        public string InstrumentMake { get; set; }
        public string InstrumentType { get; set; }
        public string InstrumentId { get; set; }
        public Nullable<long> HeightOfMicroPhone { get; set; }
        public string ObstacleIfAny { get; set; }
        public string IsolationN { get; set; }
        public string WindType { get; set; }
        public Nullable<System.DateTime> MonitoringDate { get; set; }
        public string MonitoringTime { get; set; }
        public Nullable<long> LeqAvgDayTime { get; set; }
        public Nullable<long> LeqAvgNightTime { get; set; }
        public Nullable<long> L10AvgDayTime { get; set; }
        public Nullable<long> L10AvgNightTime { get; set; }
        public Nullable<long> L50AvgDayTime { get; set; }
        public Nullable<long> L50AvgNightTime { get; set; }
        public Nullable<long> L90AvgDayTime { get; set; }
        public Nullable<long> L90AvgNightTime { get; set; }
        public Nullable<long> LminAvgDayTime { get; set; }
        public Nullable<long> LminAvgNightTime { get; set; }
        public Nullable<long> LmaxAvgDayTime { get; set; }
        public Nullable<long> LmaxAvgNightTime { get; set; }
        public Nullable<long> DistancefrmSource { get; set; }
        public string ProminentNoiseSource { get; set; }
        public Nullable<long> BackgroundNoiselevel { get; set; }
        public bool IsActive { get; set; }
        public int EnteredBy { get; set; }
        public System.DateTime EnteredDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public byte[] ModifiedDate { get; set; }
    
        public virtual SampleCollection SampleCollection { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FieldNoiseSourceParameter> FieldNoiseSourceParameters { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FieldNoiseLevelMonitoringParameter> FieldNoiseLevelMonitoringParameters { get; set; }
        public virtual StatusMaster StatusMaster { get; set; }
    }
}
