//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LIMS_DEMO.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class InventoryMaintAndCalibBreakDown
    {
        public long InventoryMaintAndCalibBreakDownId { get; set; }
        public long ItemMasterId { get; set; }
        public long InventoryBasicItemDetailsId { get; set; }
        public long InventoryBasicDetailId { get; set; }
        public Nullable<bool> IsRepair { get; set; }
        public string ProblemDescription { get; set; }
        public string ProblemReportedBy { get; set; }
        public Nullable<System.DateTime> ProblemReportedDate { get; set; }
        public string NameOfAgency { get; set; }
        public Nullable<System.DateTime> DateOfStartRepair { get; set; }
        public Nullable<System.DateTime> DateOfCompletionRepair { get; set; }
        public string MaintenanceInspectedBy { get; set; }
        public Nullable<long> Expenses { get; set; }
        public string Remark { get; set; }
    }
}
