//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LIMS_DEMO.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class InventoryBasicItemDetail
    {
        public int ID { get; set; }
        public Nullable<int> InventoryBasicDetailsID { get; set; }
        public string BatchNumber { get; set; }
        public string ModelNumber { get; set; }
        public string BarcodeNumber { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public string Description { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<int> InsertedBy { get; set; }
        public Nullable<System.DateTime> InsertedDate { get; set; }
        public Nullable<int> UpdatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<bool> IsAssigned { get; set; }
        public string InventoryBasicItemDetailsNumber { get; set; }
        public string ManufacturerName { get; set; }
        public Nullable<System.DateTime> DOM { get; set; }
        public Nullable<System.DateTime> DOE { get; set; }
        public string LOTNo { get; set; }
        public string SRNO { get; set; }
    }
}
