//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LIMS_DEMO.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvoiceRejectDetail
    {
        public long InvoiceRejectDetailsId { get; set; }
        public Nullable<long> InvoiceDetailsId { get; set; }
        public Nullable<long> EnquirySampleID { get; set; }
        public Nullable<long> CostingId { get; set; }
        public string Remarks { get; set; }
        public bool IsActive { get; set; }
        public int EnteredBy { get; set; }
        public System.DateTime EnteredDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public byte[] ModifiedDate { get; set; }
    }
}
