//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LIMS_DEMO.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemMaster
    {
        public long ItemMasterId { get; set; }
        public int CatagoryMasterId { get; set; }
        public Nullable<int> UnitId { get; set; }
        public string NameOfStock { get; set; }
        public string Code { get; set; }
        public string MinimumStock { get; set; }
        public bool IsActive { get; set; }
        public int EnteredBy { get; set; }
        public System.DateTime EnteredDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public byte[] ModifiedDate { get; set; }
    
        public virtual UnitMaster UnitMaster { get; set; }
    }
}
