//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LIMS_DEMO.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class LabDisciplineMapping
    {
        public int LabDisciplineMappingId { get; set; }
        public int LabMasterId { get; set; }
        public int LabFieldAndDisciplineId { get; set; }
        public Nullable<bool> IsAccredited { get; set; }
        public string ConformityAssessmentId { get; set; }
        public Nullable<System.DateTime> AccreditationValidTill { get; set; }
        public bool IsActive { get; set; }
        public int EnteredBy { get; set; }
        public System.DateTime EnteredDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public byte[] ModifiedDate { get; set; }
    }
}
