//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LIMS_DEMO.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class LabMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LabMaster()
        {
            this.EnquiryParameterDetails = new HashSet<EnquiryParameterDetail>();
            this.EnquiryMasters = new HashSet<EnquiryMaster>();
            this.LabMaster1 = new HashSet<LabMaster>();
        }
    
        public int LabMasterId { get; set; }
        public Nullable<int> ParentID { get; set; }
        public byte LabTypeId { get; set; }
        public byte BranchCategoryId { get; set; }
        public string LabBranchName { get; set; }
        public string LabBranchCode { get; set; }
        public string Description { get; set; }
        public Nullable<int> CountryCode { get; set; }
        public string ContactNo { get; set; }
        public string MobileNo { get; set; }
        public string Email { get; set; }
        public System.DateTime SubscriptionDate { get; set; }
        public string SubscriptionKey { get; set; }
        public Nullable<bool> IsNABLAccredited { get; set; }
        public string ConformityAssessmentId { get; set; }
        public Nullable<System.DateTime> AccreditationValidity { get; set; }
        public string VerificationCode { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string WardNo { get; set; }
        public string Taluka { get; set; }
        public string Village { get; set; }
        public string CityName { get; set; }
        public string StateName { get; set; }
        public string CountryName { get; set; }
        public string Pincode { get; set; }
        public bool IsActive { get; set; }
        public int EnteredBy { get; set; }
        public System.DateTime EnteredDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public byte[] ModifiedDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EnquiryParameterDetail> EnquiryParameterDetails { get; set; }
        public virtual BranchCategoryMaster BranchCategoryMaster { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EnquiryMaster> EnquiryMasters { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LabMaster> LabMaster1 { get; set; }
        public virtual LabMaster LabMaster2 { get; set; }
        public virtual LabTypeMaster LabTypeMaster { get; set; }
    }
}
