//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LIMS_DEMO.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lims_DisposalCollection
    {
        public long DisposalCollectionId { get; set; }
        public long SampleTypeProductId { get; set; }
        public string SampleTypeProductName { get; set; }
        public string SampleCode { get; set; }
        public string DateofRecieptofSample { get; set; }
        public string DateofReporting { get; set; }
        public Nullable<System.DateTime> DateofDisposal { get; set; }
        public string DisposalMethod { get; set; }
        public string DisposedBy { get; set; }
        public string SuperwisedBy { get; set; }
        public string Remarks { get; set; }
        public Nullable<long> SampleCollectionId { get; set; }
    
        public virtual Lims_DisposalCollection Lims_DisposalCollection1 { get; set; }
        public virtual Lims_DisposalCollection Lims_DisposalCollection2 { get; set; }
    }
}
