//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LIMS_DEMO.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lims_IsFieldCombineResult
    {
        public long ParameterId { get; set; }
        public string ParameterName { get; set; }
        public string Unit { get; set; }
        public Nullable<decimal> Result { get; set; }
        public Nullable<int> PCBLimit { get; set; }
        public string TestMethod { get; set; }
    }
}
