//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LIMS_DEMO.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class LocationSampleCollection
    {
        public long LocationSampleCollectionID { get; set; }
        public long EnquirySampleId { get; set; }
        public int SampleLocationId { get; set; }
        public string LocationSampleName { get; set; }
        public Nullable<int> SampleCollectedBy { get; set; }
        public bool IsActive { get; set; }
        public int EnteredBy { get; set; }
        public System.DateTime EnteredDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public byte[] ModifiedDate { get; set; }
        public string SampleNameOriginal { get; set; }
        public Nullable<int> WorkOrderId { get; set; }
    
        public virtual EnquirySampleDetail EnquirySampleDetail { get; set; }
        public virtual SampleLocation SampleLocation { get; set; }
    }
}
