//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LIMS_DEMO.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class MenuMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MenuMaster()
        {
            this.MenuRoleBranchMappings = new HashSet<MenuRoleBranchMapping>();
            this.MenuMaster1 = new HashSet<MenuMaster>();
        }
    
        public int MenuMasterId { get; set; }
        public Nullable<int> ParentId { get; set; }
        public string Menu { get; set; }
        public string Description { get; set; }
        public Nullable<int> SequenceNo { get; set; }
        public string IconValues { get; set; }
        public string TargetUrl { get; set; }
        public bool IsActive { get; set; }
        public int EnteredBy { get; set; }
        public System.DateTime EnteredDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public byte[] ModifiedDate { get; set; }
        public Nullable<int> MenuHead { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MenuRoleBranchMapping> MenuRoleBranchMappings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MenuMaster> MenuMaster1 { get; set; }
        public virtual MenuMaster MenuMaster2 { get; set; }
    }
}
