//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LIMS_DEMO.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ParameterFormula
    {
        public long ParameterFormulaID { get; set; }
        public long ParameterMasterId { get; set; }
        public int ParameterGroupId { get; set; }
        public int TestMethodID { get; set; }
        public int UnitID { get; set; }
        public byte DisciplineId { get; set; }
        public int FormulaSrNo { get; set; }
        public string Notation { get; set; }
        public string DisplayName { get; set; }
        public string Formula { get; set; }
        public Nullable<bool> IsFDV { get; set; }
        public string NotationValue { get; set; }
        public Nullable<int> Unit { get; set; }
        public Nullable<int> DataType { get; set; }
        public Nullable<int> Precision { get; set; }
        public bool IsActive { get; set; }
        public int EnteredBy { get; set; }
        public System.DateTime EnteredDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    
        public virtual DisciplineMaster DisciplineMaster { get; set; }
        public virtual ParameterGroupMaster ParameterGroupMaster { get; set; }
        public virtual ParameterMaster ParameterMaster { get; set; }
        public virtual TestMethod TestMethod { get; set; }
        public virtual UnitMaster UnitMaster { get; set; }
    }
}
