//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LIMS_DEMO.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ParameterMapping
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ParameterMapping()
        {
            this.EnquiryParameterDetails = new HashSet<EnquiryParameterDetail>();
            this.FieldAmbientAirGasesSamplings = new HashSet<FieldAmbientAirGasesSampling>();
            this.FieldWasteWaters = new HashSet<FieldWasteWater>();
        }
    
        public int ParameterMappingId { get; set; }
        public long ParameterMasterId { get; set; }
        public int ParameterGroupId { get; set; }
        public Nullable<int> UnitId { get; set; }
        public Nullable<int> TestMethodId { get; set; }
        public string PCBUpper { get; set; }
        public string PCBLower { get; set; }
        public string RegulatoryMin { get; set; }
        public string RegulatoryMax { get; set; }
        public Nullable<bool> IsRegAgrbl { get; set; }
        public string PermissibleMin { get; set; }
        public string PermissibleMax { get; set; }
        public Nullable<bool> IsPermisbleAgrbl { get; set; }
        public string LOD { get; set; }
        public string LOQ { get; set; }
        public Nullable<bool> IsPresentLOD { get; set; }
        public Nullable<bool> InField { get; set; }
        public Nullable<bool> InLab { get; set; }
        public Nullable<bool> IsDefaultUnit { get; set; }
        public string SampleMedia { get; set; }
        public Nullable<decimal> MinTestingRange { get; set; }
        public string MaxTestingRange { get; set; }
        public bool IsActive { get; set; }
        public int EnteredBy { get; set; }
        public System.DateTime EnteredDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public byte[] ModifiedDate { get; set; }
        public Nullable<bool> IsNABLAccredited { get; set; }
        public Nullable<byte> DisciplineId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EnquiryParameterDetail> EnquiryParameterDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FieldAmbientAirGasesSampling> FieldAmbientAirGasesSamplings { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FieldWasteWater> FieldWasteWaters { get; set; }
        public virtual ParameterGroupMaster ParameterGroupMaster { get; set; }
        public virtual DisciplineMaster DisciplineMaster { get; set; }
        public virtual ParameterMaster ParameterMaster { get; set; }
        public virtual TestMethod TestMethod { get; set; }
        public virtual UnitMaster UnitMaster { get; set; }
    }
}
