//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LIMS_DEMO.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentDetail
    {
        public long PaymentDetailsId { get; set; }
        public string RecieptNo { get; set; }
        public Nullable<decimal> PaidAmount { get; set; }
        public System.DateTime PayDate { get; set; }
        public int PaymentMode { get; set; }
        public string BankName { get; set; }
        public string DD_ChequeNo_Neft { get; set; }
        public System.DateTime DD_ChequeDate { get; set; }
        public int EnteredBy { get; set; }
        public System.DateTime EnteredDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string BranchName { get; set; }
        public string RegistrationName { get; set; }
        public string WorkOrderNo { get; set; }
        public string InvoiceNumber { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
        public Nullable<long> EnquirySampleId { get; set; }
    }
}
