//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LIMS_DEMO.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchaseRecord
    {
        public int PurchaseRecordID { get; set; }
        public string QtyReceived { get; set; }
        public string GradeReceived { get; set; }
        public string BrandReceived { get; set; }
        public Nullable<int> DeliveryTime { get; set; }
        public string DeliveryChallanNo { get; set; }
        public Nullable<System.DateTime> DeliveryChallanDate { get; set; }
        public string ConditionOfPackaging { get; set; }
        public string IntegrityOfPackaging { get; set; }
        public string BillNo { get; set; }
        public Nullable<System.DateTime> BillDate { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<short> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<int> EnteredBy { get; set; }
        public Nullable<System.DateTime> EnteredDate { get; set; }
        public Nullable<int> PurchaseRequestID { get; set; }
        public Nullable<int> CurrentStatus { get; set; }
        public Nullable<System.DateTime> DateOfReceive { get; set; }
        public string Remark { get; set; }
    
        public virtual PurchaseRequestDetail PurchaseRequestDetail { get; set; }
    }
}
