//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LIMS_DEMO.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SampleDescriptionMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SampleDescriptionMaster()
        {
            this.SampleCollections = new HashSet<SampleCollection>();
        }
    
        public int SampleDescriptionId { get; set; }
        public int ProductGroupId { get; set; }
        public int SubGroupId { get; set; }
        public string SampleDescription { get; set; }
        public string MatrixCode { get; set; }
        public string PrintDesc { get; set; }
        public bool IsActive { get; set; }
        public int EnteredBy { get; set; }
        public System.DateTime EnteredDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public byte[] ModifiedDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SampleCollection> SampleCollections { get; set; }
        public virtual ProductGroupMaster ProductGroupMaster { get; set; }
    }
}
