//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LIMS_DEMO.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SampleParameterFormulaValue
    {
        public long SampleParameterFormulaValueId { get; set; }
        public long ParameterFormulaID { get; set; }
        public long SampleCollectionId { get; set; }
        public int ParameterMasterId { get; set; }
        public int ParameterGroupId { get; set; }
        public string NotationValue { get; set; }
        public Nullable<bool> IsFDV { get; set; }
        public bool IsActive { get; set; }
        public int EnteredBy { get; set; }
        public System.DateTime EnteredDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public string TestingHours { get; set; }
        public Nullable<bool> IsFinalResult { get; set; }
    }
}
