//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LIMS_DEMO.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SampleParameterFile
    {
        public long SampleParameterFilesID { get; set; }
        public long SampleCollectionId { get; set; }
        public int ParameterGroupId { get; set; }
        public long ParameterMasterId { get; set; }
        public string FileName { get; set; }
        public int UserMasterID { get; set; }
        public bool IsActive { get; set; }
        public int EnteredBy { get; set; }
        public System.DateTime EnteredDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
    
        public virtual ParameterGroupMaster ParameterGroupMaster { get; set; }
        public virtual SampleCollection SampleCollection { get; set; }
        public virtual UserMaster UserMaster { get; set; }
        public virtual ParameterMaster ParameterMaster { get; set; }
    }
}
