//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LIMS_DEMO.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SampleParameterFormulaValuesTemp
    {
        public long SampleParameterFormulaValueTempId { get; set; }
        public long SampleCollectionId { get; set; }
        public int ParameterMasterId { get; set; }
        public int ParameterGroupId { get; set; }
        public string NotationValueTemp { get; set; }
        public long ParameterFormulaID { get; set; }
    }
}
