//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LIMS_DEMO.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubGroupMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SubGroupMaster()
        {
            this.EnquiryDetails = new HashSet<EnquiryDetail>();
            this.EnquiryDetails1 = new HashSet<EnquiryDetail>();
            this.ParameterGroupMasters = new HashSet<ParameterGroupMaster>();
            this.MatrixMasters = new HashSet<MatrixMaster>();
            this.TermsAndConditions = new HashSet<TermsAndCondition>();
        }
    
        public int SubGroupId { get; set; }
        public int ProductGroupId { get; set; }
        public string SubGroupName { get; set; }
        public string SubGroupCode { get; set; }
        public string Description { get; set; }
        public bool IsActive { get; set; }
        public int EnteredBy { get; set; }
        public System.DateTime EnteredDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public byte[] ModifiedDate { get; set; }
        public Nullable<int> SampleTypeProductId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EnquiryDetail> EnquiryDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EnquiryDetail> EnquiryDetails1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ParameterGroupMaster> ParameterGroupMasters { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MatrixMaster> MatrixMasters { get; set; }
        public virtual ProductGroupMaster ProductGroupMaster { get; set; }
        public virtual SampleTypeProductMaster SampleTypeProductMaster { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TermsAndCondition> TermsAndConditions { get; set; }
    }
}
