//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LIMS_DEMO.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_DailyInvoice
    {
        public int ID { get; set; }
        public string CustomerName { get; set; }
        public string WorkOrderNo { get; set; }
        public string InvoiceNo { get; set; }
        public Nullable<decimal> Totalcharge { get; set; }
        public Nullable<decimal> Discountamt { get; set; }
        public Nullable<decimal> SampleCollectioncharge { get; set; }
        public Nullable<decimal> TransportationCharge { get; set; }
        public Nullable<decimal> TestingCharge { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
        public Nullable<decimal> NetAmount { get; set; }
        public Nullable<decimal> GSTAmt { get; set; }
        public Nullable<decimal> Paidamount { get; set; }
        public Nullable<decimal> Balanceamount { get; set; }
        public Nullable<System.DateTime> InvoiceDate { get; set; }
        public Nullable<int> Count { get; set; }
        public Nullable<int> EnquirySampleID { get; set; }
        public Nullable<int> CostingId { get; set; }
        public string RejectStatus { get; set; }
    }
}
