//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LIMS_DEMO.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkOrder
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WorkOrder()
        {
            this.SampleCollections = new HashSet<SampleCollection>();
            this.WorkOrderSampleCollectionDates = new HashSet<WorkOrderSampleCollectionDate>();
        }
    
        public int WorkOrderId { get; set; }
        public Nullable<long> QuotationId { get; set; }
        public Nullable<int> AssignedToId { get; set; }
        public Nullable<System.DateTime> ExpectSampleCollDate { get; set; }
        public System.DateTime WORecieveDate { get; set; }
        public System.DateTime WOEndDate { get; set; }
        public string WOUpload { get; set; }
        public string FileName { get; set; }
        public string Status { get; set; }
        public string WorkOrderNo { get; set; }
        public string GST { get; set; }
        public string Remark { get; set; }
        public bool IsActive { get; set; }
        public int EnteredBy { get; set; }
        public System.DateTime EnteredDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public byte[] ModifiedDate { get; set; }
        public Nullable<byte> ModeOfCommunicationId { get; set; }
        public Nullable<int> CustomerMasterId { get; set; }
        public Nullable<byte> StatusId { get; set; }
        public Nullable<int> LabMasterId { get; set; }
        public Nullable<long> Duration { get; set; }
        public Nullable<bool> IsIGST { get; set; }
        public string ContractAmendment { get; set; }
        public string DeliverBy { get; set; }
        public Nullable<int> DeliverId { get; set; }
        public Nullable<bool> OVC { get; set; }
    
        public virtual Quotation Quotation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SampleCollection> SampleCollections { get; set; }
        public virtual UserMaster UserMaster { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WorkOrderSampleCollectionDate> WorkOrderSampleCollectionDates { get; set; }
    }
}
