//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LIMS_DEMO.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkOrderSampleCollectionDate
    {
        public int WorkOrderSampleCollectionDateId { get; set; }
        public Nullable<int> WorkOrderId { get; set; }
        public Nullable<System.DateTime> ExpectSampleCollDate { get; set; }
        public Nullable<System.DateTime> ActualSampleCollDate { get; set; }
        public Nullable<int> Status { get; set; }
        public bool IsActive { get; set; }
        public int EnteredBy { get; set; }
        public System.DateTime EnteredDate { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public byte[] ModifiedDate { get; set; }
        public Nullable<long> Duration { get; set; }
        public Nullable<int> WOMasterSampleCollectionDateId { get; set; }
        public Nullable<long> EnquirySampleID { get; set; }
        public Nullable<long> LocationSampleCollectionID { get; set; }
        public string LocationSampleName { get; set; }
    
        public virtual WOMasterSampleCollectionDate WOMasterSampleCollectionDate { get; set; }
        public virtual WorkOrder WorkOrder { get; set; }
    }
}
